# Testing API endpoints using the humao.rest-client vscode extension listed in .vscode/extensions.json
# Api key and other global vars are defines in .vscode/settings.json "rest-client.environmentVariables"

@itemsLimit = 5
@productId = 2


### List Products
GET {{fakestoreFakeApiBase}}products?limit={{itemsLimit}}

### Single Product
GET {{fakestoreFakeApiBase}}products/{{productId}}
