# Testing API endpoints using the humao.rest-client vscode extension listed in .vscode/extensions.json
# Api key and other global vars are defines in .vscode/settings.json "rest-client.environmentVariables"

@pageIndex = 1
@userId = 1


### List Users
GET {{regressFakeApiBase}}users?page={{pageIndex}}

### Single User
GET {{regressFakeApiBase}}users/{{userId}}
