# Testing API endpoints using the humao.rest-client vscode extension listed in .vscode/extensions.json
# Api key and other global vars are defines in .vscode/settings.json "rest-client.environmentVariables"

@pageIndex = 1
@userId = 2

@regressFakeApiBase = http://localhost:3333/api/


### Get All Users
GET {{regressFakeApiBase}}users?page={{pageIndex}}

### Get Single User
GET {{regressFakeApiBase}}users/{{userId}}

### Create User
POST {{regressFakeApiBase}}users

{
    "name": "morpheus",
    "job": "leader"
}

### Update User
PUT {{regressFakeApiBase}}users/{{userId}}

{
    "name": "Jasonimoo",
    "job": "Guru"
}

### Delete User
DELETE {{regressFakeApiBase}}users/{{userId}}
